---
- name: Configure OpenVPN setup
  hosts: all

  tasks:
  - name: Prepare infrastructure
    block:
    - name: Make the direcotry 
      file:
        path: "/home/{{ ansible_ssh_user }}/client-configs/keys"
        state: directory
        mode: 0700

    - name: Run the script gen-req
      expect:
        command: "./easyrsa gen-req {{ client_name }} nopass"
        responses:
          '(.*)Common Name(.*)': ""
          '(.*)Confirm key(.*)': "no"
        chdir: "{{ easy_rsa_home }}/"
      ignore_errors: yes

    - name: Copy keys
      copy:
        src: "{{ easy_rsa_home }}/pki/private/{{ client_name }}.key"
        dest: ~/client-configs/keys/
        remote_src: true
    when: inventory_hostname == 'openvpn_server'

  - name: Copying files
    block:
      - name: Copy ".req" file from the openvpn to the master
        fetch:
          src: "{{ easy_rsa_home }}/pki/reqs/{{ client_name }}.req"
          dest: /tmp/
          flat: yes
        when: inventory_hostname == 'openvpn_server'

      - name: Copy ".req" file from the master to ca_server
        copy:
          src: "/tmp/{{ client_name }}.req"
          dest: /tmp/  
        when: inventory_hostname == 'ca_server'

  - name: Running scripts
    block:
      - name: Run the script import-req
        shell: "./easyrsa import-req /tmp/{{ client_name }}.req {{ client_name }}"
        args:
          chdir: "{{ easy_rsa_home }}/"

      - name: Run the script sign-req
        expect:
          command: "./easyrsa sign-req server {{ client_name }}"
          responses:
            '(.*)Confirm request details(.*)': "yes"
            '(.*)Enter pass phrase(.*)': "{{ pass_to_build_ca }}"
          chdir: "{{ easy_rsa_home }}/"
    when: inventory_hostname == 'ca_server'
    ignore_errors: yes

  - name: Copy files back
    block:
      - name: Copy ".crt" files from the CA server to the master
        fetch:
          src: "{{ easy_rsa_home }}/pki/issued/{{ client_name }}.crt"
          dest: /tmp/
          flat: yes
        when: inventory_hostname == 'ca_server'

      - name: Copy ".crt" files from the master to the openvpn server
        copy:
          src: "/tmp/{{ client_name }}.crt"
          dest: ~/client-configs/keys/ 
        when: inventory_hostname == 'openvpn_server'

  - name: Other configurations
    block:
      - name: Copy ta.key and copy ca.key
        copy:
          src: "{{ item }}"
          dest: "/home/{{ ansible_ssh_user }}/client-configs/keys/"
          owner: "{{ ansible_ssh_user }}"
          group: "{{ ansible_ssh_user }}"
          remote_src: true
        loop:
          - "{{ easy_rsa_home }}/ta.key"
          - "/etc/openvpn/server/ca.crt"

      - name: Configure /etc/sysctl.conf
        lineinfile:
          path: /etc/sysctl.conf
          state: present
          line: net.ipv4.ip_forward = 1

      - name: Load current state of /etc/sysctl.conf
        shell: "sysctl -p"
    become: true
    when: inventory_hostname == 'openvpn_server'
